### ISSUE TITLE
"Number Line: Operations" Master Checklist

### ISSUE THREAD

**Issue by jbphet** [phetsims/number-line-operations#1]
# "Number Line: Operations" master checklist

## Design
- [x] **Sim folder and design doc created** (Date: //)
  - [x] Create sim folder in [PhET Sim Design Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYUUhvZnlCUDF0bGc) using phet-docs account
  - [x] Place design doc in the sim folder
- [x] **Sim suggestions doc reviewed** [suggestions doc](https://phet.unfuddle.com/a#/projects/9404/notebooks/3863/pages/105821)
- [x] **Learning goals and standards identified** (Date: //)
- [x] **Design concept complete**  (Date: //)
- [x] **Wireframes complete** (Date: //)
- [x] **Mockups complete** (Date: //)
  - [x] Mockups checked for colorblind and greyscale
- [x] **Features for PhET-iO discussion**
- [x] **Interviews complete** (Date: 12/10/20)
  - [x] Results reported to team
  - [x] Notes pasted into design doc
  - [x] Back-up of interviews
- [x] **Lead designer "sign off"** (Date: 1/20/21)
  - [x] Performance acceptable
  - [x] Carefully review ?showPointerAreas
  - [x] No new feature requests
- [x] **Pre-publication items**
  - [x] Auxilary screenshots (up to 3 additional)
  - [x] Accessories (keywords, categories, description, learning goals, related sims, NSDL)
  - [x] Email announcement language
  - [x] Teacher Guide created, uploaded, and added to sim design folder
  - [ ] Sim primer draft
  - [x] [LoL icons](https://docs.google.com/document/d/1GmLNE31gs8hQYGze3xwmN9k7B6gu7lQ7wJe2phqdH9Y/edit) for each screen created and uploaded to Drive
  - [x] [LoL metadata](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=562591429) for each screen (description, vocab words, questions for before/after sim use)
- [ ] **Post-publication items**
  - [ ] Share new features, design challenges, and treats with group!
  - [x] Email announcement
  - [x] Deliver to [Legends of Learning](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0)
  - [x] Sim primer (create issue, publish ideally within 1 month of live sim)
  - [ ] Hold postmortem if applicable (Date: //)

## Implementation
- [x] **Repository created** (Date: 3/5/2020)
  - [x] Simulation added to [responsible_dev.md](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.md)
  - [x] Use `grunt create-sim` in perennial (see `--help` for arguments) to create the repository structure
  - [x] Collaborators added (Developer team, QA team, designers, etc)
  - [x] standard GitHub label set applied
  - [x] repository added to perennial/data/active-repos
- [x] **Development started** (Date: 3/6/2020)
- [x] **Sim is "feature complete"** (Date: Dec 2021)
- [x] **Code review completed** (Date: 1/4/2021)
- [x] **Pre-publication items**
  - [x] Main screenshot (read [this](https://github.com/phetsims/QA/blob/master/doc/qa-book.md#screenshots))
  - [x] Verify credits with lead (Team, Contributors, QA, Graphic Arts, Sound Design, any Thanks)
- [x] **Published** (Date: 2/3/2021)
  - [x] Mark the sim as published in [responsible_dev.md](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.md)

## QA
- [x] **Dev testing started** (Date: 12/23/20)
- [x] **Dev testing completed** (Date: 1/20/21)
- [x] **First RC published** (Date: 1/26/2021)
  - [x] Test matrices put in [Testing Matrices Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYbW9fTGNCODdYVjQ)
- [x] **RC testing completed** (Date: 2/1/2021)

**Comment by jbphet** [comment]
Assigning to @amanda-phet to update the parts about document creation and interviews, since we've started on interviews.

**Comment by jbphet** [comment]
I've updated the information related to testing and publication from the development side.  @amanda-phet - I think the rest is up to you, feel free to assign back if I've missed anything.

**Comment by amanda-phet** [comment]
When we finally have another status meeting we can make the announcement to the team and share the features of the sim. 

I'm not sure what to do about Gooru and Edmodo. @kathy-phet is that still something we are doing?

**Comment by amanda-phet** [comment]
Everything here is complete, and when we finally have a status meeting I'll share the sim with the team :)
